---
- hosts: all
  remote_user: root
  gather_facts: False
  roles:
    - { role: ~/ansible-role-dropshare }
    - { role: ~/bin/roles/ansible-role-degoss-directories_fix, version: "0.3.1", tests: ["~/ansible-role-dropshare/circle/goss_tests/goss.yml"] }


  vars:
    server_hostname: 'myserver.internal'
    pub_key_location: '~/ansible-role-dropshare/circle/test.pub'
    ssl_files:
      - ~/ansible-role-dropshare/circle/server.crt
      - ~/ansible-role-dropshare/circle/server.key
    pip_script_location: "~/bin/get-pip.py"

  pre_tasks:
  - name: waiting for server
    local_action: wait_for port=22 host="{{ ip_address }}"

  - pause:
      seconds: 15

  - setup:
