---
- hosts: all
  remote_user: root
  gather_facts: False
  roles:
    - { role: /home/ubuntu/dropshare }
    - { role: /home/ubuntu/dropshare/circle/tests/test_role }


  vars:
    server_hostname: 'myserver.internal'
    pub_key_location: '/home/ubuntu/dropshare/circle/test.pub'
    ssl_files:
      - /home/ubuntu/dropshare/circle/server.crt
      - /home/ubuntu/dropshare/circle/server.key

  pre_tasks:
  - name: waiting for server
    local_action: wait_for port=22 host="{{ ip_address }}"

  - pause:
      seconds: 15

  - setup:
