---
- hosts: all
  remote_user: root
  gather_facts: False
  roles:
    - { role: dropshare, dir: '../../../' }
    - { role: tests, dir: '../tests/test_role' }


  vars:
    server_hostname: 'myserver.internal'
    pub_key_location: '~/test.pub'
    ssl_files:
      - circle/ssl_certs/server.crt
      - circle/ssl_certs/server.key

  pre_tasks:
  - name: waiting for server
    local_action: wait_for port=22 host="{{ ip_address }}"

  - pause:
      seconds: 15

  - setup:
