---
- hosts: all
  remote_user: root
  gather_facts: False
  roles:
    - { role: /home/ubuntu/ansible_dropshare }
    - { role: ~/bin/roles/naftulikay.degoss, version: "0.3.1", tests: /home/ubuntu/ansible_dropshare/circle/goss_tests }


  vars:
    server_hostname: 'myserver.internal'
    pub_key_location: '/home/ubuntu/ansible_dropshare/circle/test.pub'
    ssl_files:
      - /home/ubuntu/ansible_dropshare/circle/server.crt
      - /home/ubuntu/ansible_dropshare/circle/server.key
    pip_script_location: "/home/ubuntu/bin/get-pip.py"
    tests_to_run:
      - test_default.py

  pre_tasks:
  - name: waiting for server
    local_action: wait_for port=22 host="{{ ip_address }}"

  - pause:
      seconds: 15

  - setup:
